<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handling in Socket.io</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.2/socket.io.js" integrity="sha512-VJ6+sp2E5rFQk05caiXXzQd1wBABpjEj1r5kMiLmGAAgwPItw1YpqsCCBtq8Yr1x6C49/mTpRdXtq8O2RcZhlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


</head>
<body>

     <p>Error handling in socket.io</p>

     <script>
        const socket = io();
        socket.on('connect_failed',() =>{
            alert('the connection failed')
        })
        socket.on('reconnect_failed',() =>{
            alert('the reconnection failed')
        })
     </script>
</body>
</html>